### ISSUE TITLE
Ie10 incompatibility

### ISSUE THREAD

**Issue by 3313204840** [JasonBai007/vue-seed#1]
it can not work in ie.10.how to change it to work?

**Comment by JasonBai007** [comment]
I will try to handle it.

**Comment by JasonBai007** [comment]
i installed babel-polyfill into this project, then the login page can open in IE11.
but can't go to other pages when triggering the login button.

**Comment by xumengqiang** [comment]
我部署到我本地怎么运行不了啊

**Comment by JasonBai007** [comment]
已实现对IE浏览器的兼容，具体方法请查看Readme文件
