### ISSUE TITLE
向作者请教个问题

### ISSUE THREAD

**Issue by dantegarden** [JasonBai007/vue-seed#13]
假如我有多个项目组同时开发，每个项目组负责一个子系统，前端都是vue（比如说就是您的这套代码），而且除了负责不同的业务以外几乎一样。有一个门户的vue去整合这些子系统，他管理菜单和用户角色权限，子系统在门户vue里是只是一系列菜单。
请问这个需求有什么实现方案吗？可以的话请您讲讲思路，非常感谢。

**Comment by JasonBai007** [comment]
1、首先保证所有子系统和门户的样式统一
2、编写一个子系统的初始项目，包括通用的样式布局和完整配置
3、每个项目组都拉取这个初始项目，然后以此作为自己子系统的启动模板，在上面开发
4、最后编写门户页面，编写登录登出和权限逻辑
5、最后整合的时候，可能会遇到问题，所以，可以提前写几个Hello world 子系统，整合试试，包括提前演练部署整个系统。因为我就遇到问题了。

**Comment by dantegarden** [comment]
> 1、首先保证所有子系统和门户的样式统一
> 2、编写一个子系统的初始项目，包括通用的样式布局和完整配置
> 3、每个项目组都拉取这个初始项目，然后以此作为自己子系统的启动模板，在上面开发
> 4、最后编写门户页面，编写登录登出和权限逻辑
> 5、最后整合的时候，可能会遇到问题，所以，可以提前写几个Hello world 子系统，整合试试，包括提前演练部署整个系统。因为我就遇到问题了。

感谢您的回复。但我最不明白的地方是一个vue前台要如何引入另一个独立的vue前台。我的门户系统在展示上也许只有sidebar和navbar，中间的内容部分需要另一个vue子系统来提供展示。我现在只想到iframe和异步加载html再放入div的方式，用iframe有很多弊病（比如有蒙层的弹窗和高度自适应问题），用后者又会有样式冲突（我测过两个一模一样的vue+webpack系统A引入B，会报错）。
然而实际开发时就是会有很多团队负责不同的业务系统，不知道您有没有什么其他的解决办法。

**Comment by JasonBai007** [comment]
没有做过这种大型的系统，一直在做SPA，我是想着点一个菜单，跳到另外一个系统，在新标签页打开之类的。

**Comment by dantegarden** [comment]
> 没有做过这种大型的系统，一直在做SPA，我是想着点一个菜单，跳到另外一个系统，在新标签页打开之类的。

感谢您的回复，目前我的解决方法是用vue做mpa，这是我暂时做出的示例项目
https://github.com/dantegarden/ssm-mpa-ui
但这个解决方案也不是尽善尽美，比如多页面在一起开发，如何做灰度发布，如何分开做版本管理。
我暂时还没想到办法，如果您有什么好点子希望能一起交流。

**Comment by JasonBai007** [comment]
厉害厉害
