### ISSUE TITLE
路由这块是不是可以优化一下

### ISSUE THREAD

**Issue by qyt2018** [JasonBai007/vue-seed#16]
路由解析这块可以优化一下！！！！

**Comment by JasonBai007** [comment]
怎么优化？能具体一些吗？

**Comment by JasonBai007** [comment]
我知道了，我的路由解析，是偷懒的写法，只解析两层。但考虑到目前也可以用，就懒得写递归函数了。

**Comment by superman0159** [comment]
> 我知道了，我的路由解析，是偷懒的写法，只解析两层。但考虑到目前也可以用，就懒得写递归函数了。

很荣幸大佬引用了我的教程，其实关于这个路由的解析，后面又补了一篇[文章](https://juejin.im/post/5c88a96af265da2da15dfbed)哦。

**Comment by JasonBai007** [comment]
嘿嘿，我不是大佬，比较菜，没有认真写路由解析函数。
