### ISSUE TITLE
感谢分享

### ISSUE THREAD

**Issue by peterpanBest** [JasonBai007/vue-seed#2]
感谢您的分享，能不能请教您一个问题，就是你是如何实现刷新浏览器，页面保持当前页面不跳转的，看了您的代码之后，还是不太明白。谢谢！ smile

**Comment by js1k** [comment]
用路由的话，页面刷新是不会改变路由的，如果不是用路由的话，就需要用到参数控制了吧

**Comment by peterpanBest** [comment]
谢谢！

**Comment by JasonBai007** [comment]
没事，我才看到，重点看我的路由配置，用到了嵌套路由，并且看一下Layout.vue组件。一般刷新浏览器页面不跳转啊，应该还在当前页啊。
