### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by JakeWoki** [JasonBai007/vue-seed#3]
父路由Layout使用了动画
`<router-view class="page-component-wrap animated fadeIn"></router-view>`
如果在子路由中使用饿了么的组件el-dialog，弹层会有问题，去掉动画正常。不去掉动画的情况要怎么才能正常使用el-dialog？

**Comment by JasonBai007** [comment]
我刚才给你试了半天，发现，在配置dialog组件的时候，可以添加  :append-to-body="true"，这样的话，就不受影响了，就正常了，是不是很6啊？so cool

**Comment by JakeWoki** [comment]
感谢！

**Comment by JasonBai007** [comment]
这是饿了么组件库中dialog组件（2.3.9版本，也就是最新版）官方说明文档里的。Dialog 自身是否插入至 body 元素上。嵌套的 Dialog 必须指定该属性并赋值为 true。你的情况属于嵌套的Dialog

**Comment by JakeWoki** [comment]
多谢
