### ISSUE TITLE
关于后续完善

### ISSUE THREAD

**Issue by miaoyukai** [JasonBai007/vue-seed#4]
有没有那种后台管理的常用的那些组件啊，比如说分页，增删改查的那些页面

**Comment by JasonBai007** [comment]
目前没有，因为该项目的定位是十足的装逼系统，主要受众是刚接触vue的童鞋。我不想搞得太复杂，另外，使用组件库搭建页面也不难。系统架构会搭建了。里面的页面就是小事了。后续可能会另开新项目，专门写一个通用的模板，旨在缩减开发工期。
