### ISSUE TITLE
大哥啊，这项目主界面在IE11上一片空白啊

### ISSUE THREAD

**Issue by hanzx0313** [JasonBai007/vue-seed#7]
网上找到的尽是说VUE在IE11下一片空白的，还说要加什么类库，发现此项目早已加。
而且登录页面能显示，主界面一片空白，控制台也不报错。
最后用排除法不断缩小范围发现是rythm类库的问题，望修复。（虽然我自己也已经在找修复的办法了）

**Comment by JasonBai007** [comment]
项目的readme里面，Notes条目已经说明不兼容IE的原因是rythm.js模块，目前删除这个模块的相关逻辑代码，就兼容了。

**Comment by hanzx0313** [comment]
> 项目的readme里面，Notes条目已经说明不兼容IE的原因是rythm.js模块，目前删除这个模块的相关逻辑代码，就兼容了。

好吧= =
